### ISSUE TITLE
Integrate this feature into shadowsocks-android

### ISSUE THREAD

**Issue by madeye** [twiceyuan/SSRules#2]
First of all, thanks for this awesome project. I think it's well designed and quite useful.

Maybe you can integrate your project into shadowsocks-android. I'm happy to merge your pull request.

**Comment by wongsyrone** [comment]
The author is not watching this project.
@twiceyuan

**Comment by twiceyuan** [comment]
@madeye I'm glad to hear that shadowsocks-android can add this feature. But I am not familiar with Scala and many detail from shadowsocks-android, so I may not be able to help you. 

Look forward to your update : )

**Comment by madeye** [comment]
Java is also fine. Two possible options here:

1. We define some APIs and call your app from shadowsocks to customize ACLs.
2. Integrate your activities directly into shadowsocks by Java. Then we help to convert them to Scala.

**Comment by twiceyuan** [comment]
The first option seems easier to me, but I think shadowsocks-android add this as a feature is a better thing for users (eg scan QRcode).

As for the second option, before that, I will try to build ss-android on my computer. 😅

**Comment by Mygod** [comment]
I prefer implementing this in shadowsocks-android instead of having two apps. More info will be soon posted in the issue in that repo.
