### ISSUE TITLE
一次添加多条规则

### ISSUE THREAD

**Issue by AndlsH** [twiceyuan/SSRules#4]
一次粘贴多行规则时，仅有第一行被正确处理：

![2016-12-14 20 08 06](https://cloud.githubusercontent.com/assets/9635792/21181483/1f26ad42-c239-11e6-8bb2-0444062d407e.png)

**Comment by twiceyuan** [comment]
之前没有考虑到这种用法，下个版本会考虑加上

**Comment by twiceyuan** [comment]
该项目已弃用，因为 Shadowsocks 原版项目添加了编辑规则功能，此项目不再维护，见谅。
